server:
  port: 8080

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    liquibase: DEBUG
    liquibase.executor: DEBUG
    liquibase.changelog: DEBUG
    org.springframework.boot.autoconfigure.liquibase: DEBUG