server:
  port: 8080

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,prometheus

  endpoint:
    health:
      show-details: always

  health:
    defaults:
      enabled: true
    circuitbreakers:
      enabled: true

  metrics:
    tags:
      application: product-service

  tracing:
    enabled: true
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    liquibase: INFO
    liquibase.executor: INFO
    liquibase.changelog: INFO
    org.springframework.boot.autoconfigure.liquibase: INFO